version: 0.2

env:
  variables:
    CI: "true"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest
    commands:
      - npm i --no-audit
  build:
    on-failure: ABORT
    commands:
      - npm run build
    finally:
      - npm run preview
  post_build:
    on-failure: ABORT
    commands:
      - npm run test
artifacts:
  files:
    - playwright-report/*
    - trace.zip
  name: artifact-playwright
